# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CALCULATOR.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Buvi Calculator")
        MainWindow.resize(1669, 859)
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(255, 244, 240);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 400, 471, 331))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(330, 30, 561, 761))
        self.frame.setStyleSheet("background-color: rgb(109, 243, 216);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.INPUT = QtWidgets.QLineEdit(self.frame)
        self.INPUT.setGeometry(QtCore.QRect(50, 100, 471, 61))
        self.INPUT.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.INPUT.setObjectName("INPUT")
        self.OUTPUT = QtWidgets.QLineEdit(self.frame)
        self.OUTPUT.setGeometry(QtCore.QRect(50, 180, 471, 61))
        self.OUTPUT.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.OUTPUT.setObjectName("OUTPUT")
        self.MULTIPLICATION = QtWidgets.QPushButton(self.frame)
        self.MULTIPLICATION.setGeometry(QtCore.QRect(410, 390, 101, 71))
        self.MULTIPLICATION.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.MULTIPLICATION.setCheckable(False)
        self.MULTIPLICATION.setChecked(False)
        self.MULTIPLICATION.setObjectName("MULTIPLICATION")
        self.SUBRACTION = QtWidgets.QPushButton(self.frame)
        self.SUBRACTION.setGeometry(QtCore.QRect(410, 480, 101, 71))
        self.SUBRACTION.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"")
        self.SUBRACTION.setObjectName("SUBRACTION")
        self.DIVISION = QtWidgets.QPushButton(self.frame)
        self.DIVISION.setGeometry(QtCore.QRect(410, 300, 101, 71))
        self.DIVISION.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.DIVISION.setCheckable(False)
        self.DIVISION.setChecked(False)
        self.DIVISION.setObjectName("DIVISION")
        self.ONE = QtWidgets.QPushButton(self.frame)
        self.ONE.setGeometry(QtCore.QRect(290, 570, 101, 71))
        self.ONE.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.ONE.setCheckable(False)
        self.ONE.setChecked(False)
        self.ONE.setObjectName("ONE")
        self.TWO = QtWidgets.QPushButton(self.frame)
        self.TWO.setGeometry(QtCore.QRect(170, 570, 101, 71))
        self.TWO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TWO.setCheckable(False)
        self.TWO.setChecked(False)
        self.TWO.setObjectName("TWO")
        self.THREE = QtWidgets.QPushButton(self.frame)
        self.THREE.setGeometry(QtCore.QRect(50, 570, 101, 71))
        self.THREE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.THREE.setCheckable(False)
        self.THREE.setChecked(False)
        self.THREE.setObjectName("THREE")
        self.SEVEN = QtWidgets.QPushButton(self.frame)
        self.SEVEN.setGeometry(QtCore.QRect(290, 400, 101, 71))
        self.SEVEN.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.SEVEN.setCheckable(False)
        self.SEVEN.setChecked(False)
        self.SEVEN.setObjectName("SEVEN")
        self.NINE = QtWidgets.QPushButton(self.frame)
        self.NINE.setGeometry(QtCore.QRect(50, 400, 101, 71))
        self.NINE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NINE.setCheckable(False)
        self.NINE.setChecked(False)
        self.NINE.setObjectName("NINE")
        self.SIX = QtWidgets.QPushButton(self.frame)
        self.SIX.setGeometry(QtCore.QRect(50, 480, 101, 71))
        self.SIX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SIX.setCheckable(False)
        self.SIX.setChecked(False)
        self.SIX.setObjectName("SIX")
        self.EIGHT = QtWidgets.QPushButton(self.frame)
        self.EIGHT.setGeometry(QtCore.QRect(170, 400, 101, 71))
        self.EIGHT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.EIGHT.setCheckable(False)
        self.EIGHT.setChecked(False)
        self.EIGHT.setObjectName("EIGHT")
        self.FIVE = QtWidgets.QPushButton(self.frame)
        self.FIVE.setGeometry(QtCore.QRect(170, 480, 101, 71))
        self.FIVE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FIVE.setCheckable(False)
        self.FIVE.setChecked(False)
        self.FIVE.setObjectName("FIVE")
        self.FOUR = QtWidgets.QPushButton(self.frame)
        self.FOUR.setGeometry(QtCore.QRect(290, 480, 101, 71))
        self.FOUR.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.FOUR.setCheckable(False)
        self.FOUR.setChecked(False)
        self.FOUR.setAutoRepeatDelay(300)
        self.FOUR.setObjectName("FOUR")
        self.Zero = QtWidgets.QPushButton(self.frame)
        self.Zero.setGeometry(QtCore.QRect(50, 300, 101, 71))
        self.Zero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Zero.setCheckable(False)
        self.Zero.setChecked(False)
        self.Zero.setObjectName("Zero")
        self.EQUALISE = QtWidgets.QPushButton(self.frame)
        self.EQUALISE.setGeometry(QtCore.QRect(170, 300, 101, 71))
        self.EQUALISE.setToolTipDuration(2)
        self.EQUALISE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.EQUALISE.setCheckable(False)
        self.EQUALISE.setChecked(False)
        self.EQUALISE.setObjectName("EQUALISE")
        self.ZeroZero = QtWidgets.QPushButton(self.frame)
        self.ZeroZero.setGeometry(QtCore.QRect(290, 300, 101, 71))
        self.ZeroZero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ZeroZero.setCheckable(False)
        self.ZeroZero.setChecked(False)
        self.ZeroZero.setObjectName("ZeroZero")
        self.Addition = QtWidgets.QPushButton(self.frame)
        self.Addition.setGeometry(QtCore.QRect(410, 570, 101, 71))
        self.Addition.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.Addition.setCheckable(False)
        self.Addition.setChecked(False)
        self.Addition.setObjectName("Addition")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MULTIPLICATION.setText(_translate("MainWindow", "*"))
        self.SUBRACTION.setText(_translate("MainWindow", "-"))
        self.DIVISION.setText(_translate("MainWindow", "/"))
        self.ONE.setText(_translate("MainWindow", "1"))
        self.TWO.setText(_translate("MainWindow", "2"))
        self.THREE.setText(_translate("MainWindow", "3"))
        self.SEVEN.setText(_translate("MainWindow", "7"))
        self.NINE.setText(_translate("MainWindow", "9"))
        self.SIX.setText(_translate("MainWindow", "6"))
        self.EIGHT.setText(_translate("MainWindow", "8"))
        self.FIVE.setText(_translate("MainWindow", "5"))
        self.FOUR.setText(_translate("MainWindow", "4"))
        self.Zero.setText(_translate("MainWindow", "0"))
        self.EQUALISE.setText(_translate("MainWindow", "="))
        self.ZeroZero.setText(_translate("MainWindow", "00"))
        self.Addition.setText(_translate("MainWindow", "+"))

class Calculator(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.connect_buttons()

    def connect_buttons(self):
        self.Zero.clicked.connect(lambda: self.append_number('0'))
        self.ONE.clicked.connect(lambda: self.append_number('1'))
        self.TWO.clicked.connect(lambda: self.append_number('2'))
        self.THREE.clicked.connect(lambda: self.append_number('3'))
        self.FOUR.clicked.connect(lambda: self.append_number('4'))
        self.FIVE.clicked.connect(lambda: self.append_number('5'))
        self.SIX.clicked.connect(lambda: self.append_number('6'))
        self.SEVEN.clicked.connect(lambda: self.append_number('7'))
        self.EIGHT.clicked.connect(lambda: self.append_number('8'))
        self.NINE.clicked.connect(lambda: self.append_number('9'))
        self.ZeroZero.clicked.connect(lambda: self.append_number('00'))
        self.Addition.clicked.connect(lambda: self.append_operator('+'))
        self.SUBRACTION.clicked.connect(lambda: self.append_operator('-'))
        self.MULTIPLICATION.clicked.connect(lambda: self.append_operator('*'))
        self.DIVISION.clicked.connect(lambda: self.append_operator('/'))
        self.EQUALISE.clicked.connect(self.calculate_result)

    def append_number(self, number):
        current_text = self.INPUT.text()
        new_text = current_text + number
        self.INPUT.setText(new_text)

    def append_operator(self, operator):
        current_text = self.INPUT.text()
        if current_text and current_text[-1] not in '+-*/':
            new_text = current_text + operator
            self.INPUT.setText(new_text)

    def calculate_result(self):
        try:
            expression = self.INPUT.text()
            if not all(char in '0123456789+-*/.' for char in expression):
                raise ValueError("Invalid character in expression")
            result = eval(expression)
            self.OUTPUT.setText(str(result))
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", "Invalid input. Please enter a valid expression.")
            self.INPUT.setText('')
            self.OUTPUT.setText('')

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = Calculator()
    MainWindow.show()
    sys.exit(app.exec_())
